"""Tests for the method review and the signal charts.

The review exists to be able to fail, so the tests that matter are the ones
pinning the benchmark it fails against: the same-exposure null. If `null` is
ever computed as anything other than exposure x the hold return, the review
starts grading against a benchmark that is easy to beat and stops being a check.
"""

from __future__ import annotations

import os
import sys

import numpy as np
import pandas as pd
import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), os.pardir, "scripts"))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), os.pardir, "src"))

from method_review import (TURNOVER_EDGES, measure, resample,      # noqa: E402
                           roll_up, turnover_bucket)
from signal_charts import series_for, trade                        # noqa: E402


def walk(n=600, seed=3, drift=0.0005, vol=0.02):
    rng = np.random.default_rng(seed)
    idx = pd.bdate_range("2021-01-01", periods=n)
    return pd.Series(100 * np.cumprod(1 + rng.normal(drift, vol, n)), index=idx)


# --------------------------------------------------------------------------- #
# the null
# --------------------------------------------------------------------------- #
def test_the_null_is_exposure_times_the_hold_return():
    m = measure(walk(), 0.08)
    assert m is not None
    assert np.isclose(m["null"], m["exposure"] * m["hold"])


def test_the_edge_is_the_gap_to_the_null_not_to_buy_and_hold():
    m = measure(walk(), 0.08)
    assert np.isclose(m["edge"], m["log"] - m["null"])


def test_full_exposure_makes_the_null_equal_buy_and_hold():
    s = pd.Series(100 * 1.01 ** np.arange(400),
                  index=pd.bdate_range("2021-01-01", periods=400))
    m = measure(s, 0.08)                 # never flips red in a pure uptrend
    assert m["exposure"] > 0.95
    assert np.isclose(m["null"], m["hold"], rtol=0.1)


def test_sitting_in_cash_the_whole_time_gives_a_null_of_zero():
    s = pd.Series(np.full(400, 100.0),
                  index=pd.bdate_range("2021-01-01", periods=400))
    m = measure(s, 0.08)
    assert m["exposure"] == 0.0
    assert m["null"] == 0.0


def test_measure_charges_a_fee_per_round_trip():
    s = walk(seed=11)
    m = measure(s, 0.08)
    px = s.to_numpy(float)
    from paint_live import band_state
    st, _ = band_state(px, 0.08)
    gross = float(np.diff(np.log(px))[st[:-1].astype(bool)].sum())
    assert m["log"] < gross                  # net is always below gross


def test_measure_is_none_on_a_short_series():
    assert measure(walk(n=50), 0.08) is None


# --------------------------------------------------------------------------- #
# buckets and aggregation
# --------------------------------------------------------------------------- #
def test_turnover_buckets_split_at_the_documented_edges():
    assert turnover_bucket(TURNOVER_EDGES[1] * 2) == "large"
    assert turnover_bucket(TURNOVER_EDGES[0] * 2) == "mid"
    assert turnover_bucket(TURNOVER_EDGES[0] / 2) == "small"


def test_an_unknown_turnover_is_not_silently_bucketed():
    assert turnover_bucket(float("nan")) == "unknown"


def test_roll_up_is_empty_on_no_rows():
    assert roll_up([]) == {}


def test_roll_up_counts_names_and_medians_the_edge():
    rows = [{"log": 1.0, "hold": 0.0, "null": 0.0, "edge": 1.0, "exposure": 0.5,
             "trips": 3, "win": 0.5, "median_pl": 0.0, "toll": 1.2},
            {"log": -1.0, "hold": 0.0, "null": 0.0, "edge": -1.0, "exposure": 0.5,
             "trips": 5, "win": 0.4, "median_pl": -0.1, "toll": 1.3}]
    agg = roll_up(rows)
    assert agg["names"] == 2
    assert np.isclose(agg["edge"], 0.0)
    assert np.isclose(agg["beats_null"], 0.5)


def test_weekly_resample_shortens_the_series():
    s = walk(n=500)
    assert len(resample(s, "weekly")) < len(s)
    assert len(resample(s, "daily")) == len(s)


# --------------------------------------------------------------------------- #
# charts trade the same way the review measures
# --------------------------------------------------------------------------- #
def test_chart_trades_fill_on_the_next_bar_not_the_signal_bar():
    idx = pd.bdate_range("2021-01-01", periods=6)
    df = pd.DataFrame({"open": [100, 100, 100, 200, 200, 200],
                       "close": [100, 90, 99, 200, 200, 200]}, dtype=float,
                      index=idx)
    _eq, _hold, trades = trade(df, 0.08)
    buys = [t for t in trades if t["side"] == "BUY"]
    assert buys, "no buy fired"
    # the flip is generated by bar 2's close; the fill must be bar 3's open
    assert buys[0]["i"] >= 3


def test_chart_equity_starts_at_the_stated_capital():
    idx = pd.bdate_range("2021-01-01", periods=200)
    df = pd.DataFrame({"open": np.full(200, 100.0), "close": np.full(200, 100.0)},
                      index=idx)
    eq, hold, _ = trade(df, 0.08)
    assert np.isclose(eq.iloc[0], 10_000_000)
    assert np.isclose(hold.iloc[0], 10_000_000, rtol=0.01)


def test_weekly_series_for_keeps_open_and_close():
    idx = pd.bdate_range("2021-01-01", periods=60)
    df = pd.DataFrame({"open": np.arange(60.0), "close": np.arange(60.0) + 1},
                      index=idx)
    w = series_for(df, "weekly")
    assert list(w.columns) == ["open", "close"]
    assert len(w) < len(df)
